# Generated by Django 5.2.13 on 2026-06-01 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingInstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя / название')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('city_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес / район')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('transmission', models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('both', 'Обе')], default='both', max_length=16)),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Стаж (лет)')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена за час, ₽')),
                ('price_exam_package', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Пакет к экзамену, ₽')),
                ('services_text', models.CharField(blank=True, default='', help_text='Через запятую: город, площадка, экзамен…', max_length=500, verbose_name='Услуги')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='В каталоге')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Инструктор')),
            ],
            options={
                'verbose_name': 'Автоинструктор',
                'verbose_name_plural': 'Автоинструкторы',
                'ordering': ['name', 'pk'],
            },
        ),
    ]
