# Generated by Django 5.2.13 on 2026-04-24 14:09

import apps.classifieds.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0022_servicesection_landing_faq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Раздел запчастей')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Слаг')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел запчастей',
                'verbose_name_plural': 'Разделы запчастей',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('part', 'Автозапчасть'), ('car', 'Автомобиль')], db_index=True, max_length=16, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('city_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
                ('condition', models.CharField(blank=True, choices=[('new', 'Новая'), ('used', 'Б/у')], default='', max_length=16, verbose_name='Состояние')),
                ('car_model', models.CharField(blank=True, default='', max_length=120, verbose_name='Модель')),
                ('car_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год')),
                ('car_mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег, км')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('car_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_ads', to='stations.carbrand', verbose_name='Марка авто')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('part_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_ads', to='stations.carbrand', verbose_name='Марка авто (для запчасти)')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AdPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.classifieds.models.ad_photo_upload_to, verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='classifieds.ad', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Фото объявления',
                'verbose_name_plural': 'Фото объявлений',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AutoShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Слаг')),
                ('city_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autoshop_profile', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Автомагазин',
                'verbose_name_plural': 'Автомагазины',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='classifieds.autoshopprofile', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='ad',
            name='part_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='classifieds.partcategory', verbose_name='Раздел запчастей'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['kind', 'is_published', '-created_at'], name='classifieds_kind_6aa059_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['owner', '-created_at'], name='classifieds_owner_i_bd4a70_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['shop', '-created_at'], name='classifieds_shop_id_577189_idx'),
        ),
    ]
