# Generated by Django 5.2.13 on 2026-04-24

from django.db import migrations


def seed_part_categories(apps, schema_editor):
    PartCategory = apps.get_model("classifieds", "PartCategory")

    rows = [
        ("Ходовая", "hodovaya"),
        ("Тормозная система", "tormoznaya-sistema"),
        ("Рулевое", "rulevoe"),
        ("Двигатель", "dvigatel"),
        ("Трансмиссия", "transmissiya"),
        ("Электрика / электроника", "elektrika"),
        ("Кузов", "kuzov"),
        ("Оптика", "optika"),
        ("Салон", "salon"),
        ("Охлаждение / отопление", "ohlazhdenie-otoplenie"),
        ("Топливная система", "toplivnaya-sistema"),
        ("Выхлоп", "vyhlop"),
        ("Расходники / масла / фильтры", "rashodniki"),
        ("Шины / диски", "shiny-diski"),
    ]

    for i, (name, slug) in enumerate(rows, start=1):
        PartCategory.objects.update_or_create(
            slug=slug,
            defaults={"name": name, "sort_order": i},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("classifieds", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_part_categories, migrations.RunPython.noop),
    ]

