# Generated by Django 5.2.13 on 2026-04-24 15:02

import apps.classifieds.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_seed_part_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adphoto',
            name='image',
            field=models.ImageField(upload_to=apps.classifieds.models.ad_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), message='Допустимы только изображения JPG, PNG или WEBP.')], verbose_name='Фото'),
        ),
    ]
