# Generated by Django 5.2.13 on 2026-04-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_ad_photo_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCallProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True, verbose_name='Добавочный (DTMF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_proxy', to='classifieds.ad', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Подменный звонок (добавочный)',
                'verbose_name_plural': 'Подменные звонки (добавочные)',
            },
        ),
    ]
