# Generated by Django 5.2.13 on 2026-04-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_ad_call_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='car_body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('wagon', 'Универсал'), ('suv', 'Внедорожник / кроссовер'), ('coupe', 'Купе'), ('convertible', 'Кабриолет'), ('van', 'Минивэн'), ('pickup', 'Пикап'), ('liftback', 'Лифтбек'), ('other', 'Другое')], db_index=True, default='', max_length=20, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_color',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_drive',
            field=models.CharField(blank=True, choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный'), ('other', 'Другое')], db_index=True, default='', max_length=16, verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_engine_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например: 2.0 (литры).', max_digits=4, null=True, verbose_name='Объём двигателя, л'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_fuel',
            field=models.CharField(blank=True, choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ (ГБО)'), ('hybrid', 'Гибрид'), ('electric', 'Электро'), ('other', 'Другое')], db_index=True, default='', max_length=16, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_generation',
            field=models.CharField(blank=True, default='', help_text='Например: III рестайлинг, X167 — по желанию.', max_length=120, verbose_name='Поколение / рестайлинг'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_not_crashed',
            field=models.BooleanField(blank=True, help_text='Пусто — не указано.', null=True, verbose_name='Не битый / не участвовал в ДТП'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_owners_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Число владельцев по ПТС'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_power_hp',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность, л.с.'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_steering',
            field=models.CharField(blank=True, choices=[('left', 'Левый'), ('right', 'Правый')], default='', max_length=8, verbose_name='Руль'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_transmission',
            field=models.CharField(blank=True, choices=[('mt', 'Механика'), ('at', 'Автомат'), ('cvt', 'Вариатор'), ('amt', 'Робот'), ('other', 'Другое')], db_index=True, default='', max_length=16, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='ad',
            name='car_vin',
            field=models.CharField(blank=True, default='', help_text='Необязательно. На сайте показывается частично.', max_length=32, verbose_name='VIN'),
        ),
    ]
