# Generated by Django 5.2.13 on 2026-04-25 17:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0005_ad_car_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshopprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='autoshopprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Координаты для карты. При включённом GEOCODING_ENABLED заполняется из адреса через Nominatim.', null=True, srid=4326, verbose_name='Точка на карте (WGS 84)'),
        ),
    ]
