# Generated by Django 5.2.13 on 2026-04-25 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifieds", "0006_autoshopprofile_address_autoshopprofile_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteAd",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="classifieds.ad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное объявление",
                "verbose_name_plural": "Избранные объявления",
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "ad"), name="uniq_favorite_ad_user_ad"),
                ],
            },
        ),
    ]

