# Generated by Django 5.2.13 on 2026-04-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0013_favoriteshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoshopprofile',
            options={'ordering': ['name', 'pk'], 'verbose_name': 'Автомагазин/разборка/автосалон', 'verbose_name_plural': 'Автомагазины/разборки/автосалоны'},
        ),
        migrations.RenameIndex(
            model_name='sellerreview',
            new_name='classifieds_seller__2852ea_idx',
            old_name='clsfd_sellrev_seller_stat_cr',
        ),
    ]
