# Generated by Django 5.2.13 on 2026-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0016_ad_moderation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='unpublish_reason',
            field=models.CharField(blank=True, choices=[('sold', 'Продал(а)'), ('not_available', 'Нет в наличии'), ('changed_mind', 'Передумал(а)'), ('wrong_price', 'Ошибка в цене'), ('other', 'Другая причина')], db_index=True, default='', max_length=32, verbose_name='Причина снятия'),
        ),
        migrations.AddField(
            model_name='ad',
            name='unpublish_reason_text',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий к причине'),
        ),
        migrations.AddField(
            model_name='ad',
            name='unpublished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Снято с публикации'),
        ),
    ]
