# Generated by Django 5.2.13 on 2026-05-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifieds", "0017_ad_unpublish_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="car_deal_type",
            field=models.CharField(
                choices=[("sale", "Продажа"), ("rent", "Аренда")],
                db_index=True,
                default="sale",
                help_text="Продажа или аренда. Используется только для объявлений типа «Автомобиль».",
                max_length=12,
                verbose_name="Сделка (для авто)",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="rent_price_day_rub",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="Цена аренды, ₽/сутки"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="rent_price_hour_rub",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="Цена аренды, ₽/час"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="rent_vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("car", "Аренда авто"), ("special", "Аренда спецтехники")],
                db_index=True,
                default="",
                help_text="Для аренды: авто или спецтехника. Для продажи пусто.",
                max_length=12,
                verbose_name="Тип аренды",
            ),
        ),
    ]

