# Generated by Django 4.2.26 on 2026-04-14 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('privacy', 'Политика конфиденциальности'), ('user_agreement', 'Пользовательское соглашение'), ('pd_consent', 'Согласие на обработку персональных данных'), ('sto_offer', 'Лицензионный договор-оферта (СТО)'), ('infosec_policy', 'Политика информационной безопасности'), ('paid_services', 'Оферта на оказание платных услуг')], db_index=True, max_length=32, verbose_name='Тип документа')),
                ('version_label', models.CharField(help_text='Например "1.0" или дата релиза.', max_length=64, verbose_name='Версия (метка)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок для отображения')),
                ('effective_at', models.DateTimeField(db_index=True, help_text='Документ считается действующим с этого момента (UTC хранится, показ в МСК на фронте при необходимости).', verbose_name='Дата вступления в силу')),
                ('content_markdown', models.TextField(help_text='Исходник для публичной страницы; рендер с санитизацией HTML.', verbose_name='Текст в Markdown')),
                ('content_checksum', models.CharField(editable=False, max_length=64, verbose_name='SHA-256 текста')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Версия юридического документа',
                'verbose_name_plural': 'Версии юридических документов',
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Принято')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Опционально: фиксируйте только при согласии с юристом (минимизация ПДн).', null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=256, verbose_name='User-Agent (укороченный)')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_consents', to='legal.legaldocumentversion', verbose_name='Версия документа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_consents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Согласие пользователя',
                'verbose_name_plural': 'Согласия пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='legaldocumentversion',
            index=models.Index(fields=['key', '-effective_at'], name='legal_legal_key_373069_idx'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.UniqueConstraint(fields=('key', 'version_label'), name='legal_unique_key_version_label'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user', '-accepted_at'], name='legal_userc_user_id_c94746_idx'),
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.UniqueConstraint(fields=('user', 'document_version'), name='legal_unique_user_document_version'),
        ),
    ]
