# Generated by Django 5.2.13 on 2026-04-30 14:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_paymentintent_amount'),
        ('classifieds', '0017_ad_unpublish_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('payout_details', models.CharField(help_text='Например: карта ****1234 / СБП / банк. MVP: текст, т.к. вывод ручной.', max_length=200, verbose_name='Реквизиты для выплаты')),
                ('reason', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('paid', 'Выплачено')], db_index=True, default='pending', max_length=20)),
                ('admin_comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий администратора')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='billing.wallet', verbose_name='Кошелёк')),
            ],
            options={
                'verbose_name': 'Заявка на вывод',
                'verbose_name_plural': 'Заявки на вывод',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ClassifiedsDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Создана'), ('payment_pending', 'Ожидает оплаты'), ('funds_held', 'Оплачено (холд)'), ('waiting_shipment', 'Ожидает отправки/встречи'), ('shipped', 'Отправлено'), ('buyer_confirmed', 'Получено покупателем'), ('released', 'Завершено (средства доступны продавцу)'), ('canceled', 'Отменено'), ('refund_pending', 'Возврат в обработке'), ('refunded', 'Возвращено')], db_index=True, default='created', max_length=32)),
                ('delivery_kind', models.CharField(choices=[('meetup', 'Самовывоз/встреча'), ('delivery', 'Доставка')], default='meetup', max_length=16)),
                ('provider', models.CharField(choices=[('yookassa', 'ЮKassa')], default='yookassa', max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seller_marked_shipped_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_confirm_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='classifieds.ad', verbose_name='Объявление')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classifieds_deals_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classifieds_deals_seller', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Сделка по объявлению',
                'verbose_name_plural': 'Сделки по объявлениям',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='billing_classifieds_deal_provider_payment_uniq')],
            },
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('credit', 'Поступление'), ('debit', 'Списание')], max_length=10)),
                ('kind', models.CharField(choices=[('deal_hold', 'Холд по сделке'), ('deal_release', 'Релиз по сделке'), ('refund', 'Возврат покупателю'), ('withdrawal_request', 'Заявка на вывод'), ('withdrawal_approved', 'Вывод подтверждён'), ('manual_adjust', 'Ручная корректировка'), ('fee', 'Комиссия')], db_index=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('external_id', models.CharField(blank=True, default='', help_text='Идентификатор у провайдера/внешней системы для идемпотентности (например provider_payment_id).', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='billing.wallet', verbose_name='Кошелёк')),
            ],
            options={
                'verbose_name': 'Запись кошелька',
                'verbose_name_plural': 'Записи кошелька',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('wallet', 'kind', 'external_id'), name='billing_wallet_entry_wallet_kind_external_uniq')],
            },
        ),
    ]
