# Generated by Django 5.2.13 on 2026-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_classifieds_deals_wallet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='walletledgerentry',
            name='billing_wallet_entry_wallet_kind_external_uniq',
        ),
        migrations.AddConstraint(
            model_name='walletledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('wallet', 'kind', 'direction', 'external_id'), name='billing_wallet_entry_wallet_kind_external_uniq'),
        ),
    ]
