# Generated by Django 5.2.13 on 2026-04-13 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(max_length=220, unique=True, verbose_name="Слаг")),
                ("address", models.CharField(max_length=500, verbose_name="Адрес")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[("free", "Free"), ("basic", "Basic")],
                        default="basic",
                        max_length=20,
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "subscription_paid_until",
                    models.DateField(
                        blank=True,
                        help_text="Для basic: день включительно. Для free не обязательно.",
                        null=True,
                        verbose_name="Подписка оплачена до",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_stations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "СТО",
                "verbose_name_plural": "СТО",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="stations/%Y/%m/", verbose_name="Фото")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="stations.servicestation",
                        verbose_name="СТО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото СТО",
                "verbose_name_plural": "Фото СТО",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="WorkBay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Пост / бокс")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bays",
                        to="stations.servicestation",
                        verbose_name="СТО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="servicestation",
            index=models.Index(
                fields=["is_active", "subscription_plan"], name="stations_se_is_acti_2b4977_idx"
            ),
        ),
    ]
