# Generated by Django 5.2.13 on 2026-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicestation",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Выключенные СТО не отображаются в публичном каталоге.",
                verbose_name="Активна",
            ),
        ),
        migrations.AlterField(
            model_name="servicestation",
            name="subscription_paid_until",
            field=models.DateField(
                blank=True,
                help_text="Для Basic: последний день включительно показа в каталоге; пустое значение — не показываем. Для Free поле не используется.",
                null=True,
                verbose_name="Подписка оплачена до",
            ),
        ),
        migrations.AlterField(
            model_name="servicestation",
            name="subscription_plan",
            field=models.CharField(
                choices=[("free", "Free"), ("basic", "Basic")],
                default="basic",
                help_text="Free — в каталоге без проверки оплаты. Basic — в каталоге только при заполненной дате «оплачено до» не раньше текущего дня.",
                max_length=20,
                verbose_name="Тариф",
            ),
        ),
    ]
