# Generated by Django 5.2.13 on 2026-04-15 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_f8_categories_imagekit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicestation',
            name='billing_blocked_at',
            field=models.DateTimeField(blank=True, help_text='Если заполнено — СТО скрыта из каталога и не принимает новые заявки (фаза F4).', null=True, verbose_name='Заблокировано биллингом'),
        ),
        migrations.AlterField(
            model_name='historicalservicestation',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalservicestation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalservicestation',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalservicestation',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalservicestation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalservicestation',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalservicestation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Выключенные СТО не отображаются в публичном каталоге.', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='historicalservicestation',
            name='subscription_paid_until',
            field=models.DateField(blank=True, help_text='Для Basic: последний день включительно показа в каталоге; пустое значение — не показываем. Для Free поле не используется.', null=True, verbose_name='Подписка оплачена до'),
        ),
        migrations.AlterField(
            model_name='historicalservicestation',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic')], default='basic', help_text='Free — в каталоге без проверки оплаты. Basic — в каталоге только при заполненной дате «оплачено до» не раньше текущего дня.', max_length=20, verbose_name='Тариф'),
        ),
    ]
