# Generated by Django 5.2.13 on 2026-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_service_search_phrase'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicesearchphrase',
            new_name='stations_se_phrase__9120e6_idx',
            old_name='stations_se_phrase__f8950c_idx',
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='sprite_key',
            field=models.CharField(blank=True, help_text='ID в static/pm-brand-sprite.svg и имя static/logo/{ключ}.png (например bmw, mercedes; для VW в PNG — volkswagen).', max_length=60, verbose_name='Ключ логотипа (SVG sprite)'),
        ),
    ]
