# Generated by Django 5.2.13 on 2026-04-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0021_seed_categories_for_sections_14_17'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='landing_faq',
            field=models.JSONField(blank=True, default=list, help_text='Список объектов {"q": "вопрос", "a": "ответ"} для блока FAQ и разметки FAQPage.', verbose_name='FAQ для лендинга (JSON)'),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='landing_lead',
            field=models.TextField(blank=True, help_text='Уникальный абзац для SEO (plain text). Пусто — только общий шаблон.', verbose_name='Лид-текст для лендинга /razdely/'),
        ),
    ]
