# Generated by Django 5.2.13 on 2026-04-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0022_servicesection_landing_faq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicestation",
            name="parent_station",
            field=models.ForeignKey(
                blank=True,
                help_text="Если заполнено — это мастер автосервиса и отображается в каталоге как отдельный исполнитель.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="masters",
                to="stations.servicestation",
                verbose_name="Сервис-родитель (для мастеров)",
            ),
        ),
        migrations.AddField(
            model_name="historicalservicestation",
            name="parent_station",
            field=models.ForeignKey(
                blank=True,
                help_text="Если заполнено — это мастер автосервиса и отображается в каталоге как отдельный исполнитель.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="masters",
                to="stations.servicestation",
                verbose_name="Сервис-родитель (для мастеров)",
            ),
        ),
    ]

