# Generated by Django 5.2.13 on 2026-04-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0023_servicestation_parent_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicestation',
            name='parent_station',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Если заполнено — это мастер автосервиса и отображается в каталоге как отдельный исполнитель.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stations.servicestation', verbose_name='Сервис-родитель (для мастеров)'),
        ),
    ]
