# Generated by Django 5.2.13 on 2026-04-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_f1_phone_sms_axes_ready'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='phoneverificationchallenge',
            new_name='users_phone_phone_e_00ad69_idx',
            old_name='users_pvc_phone_cr_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Необязательно; для чеков и восстановления пароля.', max_length=254, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
