# Generated by Django 5.2.13 on 2026-04-18 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_savedcar_favoritestation'),
        ('users', '0004_alter_user_phone_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='stations.servicestation', verbose_name='СТО')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_stations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'избранное СТО',
                'verbose_name_plural': 'избранные СТО',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('user', 'station'), name='users_favoritestation_user_station_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SavedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(db_index=True, max_length=20, verbose_name='Госномер')),
                ('brand_model', models.CharField(blank=True, default='', max_length=200, verbose_name='Марка / модель')),
                ('vin', models.CharField(blank=True, default='', max_length=32, verbose_name='VIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cars', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'сохранённое авто',
                'verbose_name_plural': 'сохранённые авто',
                'ordering': ['-updated_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('user', 'license_plate'), name='users_savedcar_user_plate_uniq')],
            },
        ),
    ]
