# Generated by Django 5.2.13 on 2026-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_sto_chat_auto_prune_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_role',
            field=models.CharField(choices=[('driver', 'Водитель'), ('master', 'Мастер'), ('autoservice', 'Автосервис'), ('autoshop', 'Автомагазин/разборка')], db_index=True, default='driver', max_length=20, verbose_name='Роль'),
        ),
    ]
