# Generated by Django 5.2.13 on 2026-04-25 19:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_business_role"),
    ]

    @staticmethod
    def _backfill_public_id(apps, schema_editor):
        User = apps.get_model("users", "User")
        # Заполняем уникальными UUID для уже существующих пользователей
        qs = User.objects.filter(public_id__isnull=True)
        for u in qs.iterator():
            u.public_id = uuid.uuid4()
            u.save(update_fields=["public_id"])

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                null=True,
                blank=True,
                editable=False,
                help_text="Используется в публичных ссылках профиля (вместо числового id).",
                verbose_name="Публичный идентификатор",
            ),
        ),
        migrations.RunPython(_backfill_public_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Используется в публичных ссылках профиля (вместо числового id).",
                unique=True,
                verbose_name="Публичный идентификатор",
            ),
        ),
    ]

