# Generated by Django 5.2.13 on 2026-04-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritestation',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'избранный мастер / сервис', 'verbose_name_plural': 'избранные мастера и сервисы'},
        ),
    ]
