# Generated by Django 5.2.13 on 2026-04-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_contact_phone_change_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='True после перехода по ссылке из письма; при отсутствии email — не требуется.', verbose_name='Email подтверждён'),
        ),
    ]
