# Generated by Django 5.2.13 on 2026-06-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_role',
            field=models.CharField(choices=[('driver', 'Водитель'), ('master', 'Мастер'), ('autoservice', 'Автосервис'), ('autoshop', 'Автомагазин/разборка'), ('instructor', 'Автоинструктор')], db_index=True, default='driver', max_length=20, verbose_name='Роль'),
        ),
    ]
