# Generated by GPT-5.2 for WebRTC calls MVP.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classifieds", "0010_ad_call_click_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("room_name", models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Комната LiveKit")),
                (
                    "context_kind",
                    models.CharField(
                        choices=[("none", "—"), ("ad", "Объявление"), ("ad_direct", "Чат по объявлению"), ("station_direct", "Прямой чат"), ("booking_chat", "Чат по записи")],
                        db_index=True,
                        default="none",
                        max_length=20,
                        verbose_name="Контекст",
                    ),
                ),
                ("context_id", models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name="ID контекста")),
                (
                    "status",
                    models.CharField(
                        choices=[("initiated", "Инициирован"), ("ringing", "Звонит"), ("active", "Активен"), ("completed", "Завершён"), ("missed", "Пропущен"), ("declined", "Отклонён"), ("failed", "Ошибка")],
                        db_index=True,
                        default="initiated",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Начат")),
                ("ended_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершён")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="classifieds.ad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Звонящий",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "звонок",
                "verbose_name_plural": "звонки",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["caller", "receiver", "status"], name="calls_pair_status_idx"),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["receiver", "status", "created_at"], name="calls_recv_status_time_idx"),
        ),
    ]

