# Generated by Django 5.2.13 on 2026-04-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_event_t_5dda62_idx',
            old_name='audit_audit_event_t_6a55ab_idx',
        ),
    ]
