# Generated by Django 5.2.13 on 2026-04-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_admin_audit_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_path_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_method_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_actor_i_1175ab_idx',
            old_name='audit_actor_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_object__c70e22_idx',
            old_name='audit_obj_created_idx',
        ),
    ]
