# Generated by Django 5.2.13 on 2026-04-13 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("start_time", models.TimeField(verbose_name="Начало")),
                ("end_time", models.TimeField(verbose_name="Окончание")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступно для записи"),
                ),
                (
                    "reserved_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Удержание слота без подтверждённой брони (фаза 4).",
                        null=True,
                        verbose_name="Зарезервировано до",
                    ),
                ),
                (
                    "bay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="stations.workbay",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Окно записи",
                "verbose_name_plural": "Окна записи",
                "ordering": ["date", "start_time", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "car_info",
                    models.CharField(max_length=100, verbose_name="Авто (госномер / марка)"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Телефон для связи"),
                ),
                ("description", models.TextField(verbose_name="Описание проблемы")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("completed", "Завершено"),
                            ("canceled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="stations.servicestation",
                        verbose_name="СТО",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="bookings.timeslot",
                        verbose_name="Слот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["-created_at"],
            },
        ),
    ]
