# Generated by Django 5.2.13 on 2026-04-13 20:44

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_sto_confirm_deadline(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    db_alias = schema_editor.connection.alias
    for b in (
        Booking.objects.using(db_alias)
        .filter(sto_confirm_deadline__isnull=True)
        .iterator()
    ):
        b.sto_confirm_deadline = b.created_at + datetime.timedelta(hours=1)
        b.save(update_fields=["sto_confirm_deadline"], using=db_alias)


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("stations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="sto_confirm_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Истечение ожидания подтверждения СТО (создание + 1 ч).",
                null=True,
                verbose_name="Подтвердить до",
            ),
        ),
        migrations.RunPython(backfill_sto_confirm_deadline, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="bookings.timeslot",
                verbose_name="Слот",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="reserved_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Удержание слота без подтверждённой брони.",
                null=True,
                verbose_name="Зарезервировано до",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["client"], name="bookings_bo_client__0a6e46_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["station"], name="bookings_bo_station_48e8e2_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_bo_status_233e96_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["created_at"], name="bookings_bo_created_1720a2_idx"),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["bay", "date", "start_time"], name="bookings_ti_bay_id_805c8b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed"])),
                fields=("slot",),
                name="booking_slot_unique_pending_confirmed",
            ),
        ),
    ]
