# Generated by Django 5.2.13 on 2026-04-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_reschedule_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='owner_cancel_reason',
            field=models.CharField(blank=True, default='', help_text='Кратко для клиента при отмене записи из кабинета СТО.', max_length=500, verbose_name='Причина отмены (СТО)'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='owner_cancel_reason',
            field=models.CharField(blank=True, default='', help_text='Кратко для клиента при отмене записи из кабинета СТО.', max_length=500, verbose_name='Причина отмены (СТО)'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='manual_block_note',
            field=models.CharField(blank=True, default='', help_text='Комментарий при ручном закрытии слота в календаре (клиентам не показывается).', max_length=200, verbose_name='Причина закрытия (для себя)'),
        ),
    ]
