from django.urls import path

from . import views

app_name = "erp"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("cities/<int:signal_id>/ack/", views.city_signal_ack, name="city_signal_ack"),
    path("withdrawals/", views.withdrawals_list, name="withdrawals"),
    path("withdrawals/<int:withdrawal_id>/approve/", views.withdrawal_approve, name="withdrawal_approve"),
    path("withdrawals/<int:withdrawal_id>/reject/", views.withdrawal_reject, name="withdrawal_reject"),
    path("withdrawals/<int:withdrawal_id>/paid/", views.withdrawal_mark_paid, name="withdrawal_paid"),
    path("reports/funnel/", views.funnel_report, name="funnel"),
    path("reports/funnel.xlsx", views.funnel_report_xlsx, name="funnel_xlsx"),
    path("reports/activity/", views.activity_report, name="activity"),
    path("reports/activity.xlsx", views.activity_report_xlsx, name="activity_xlsx"),
    path("reports/billing/", views.billing_report, name="billing"),
    path("reports/billing.xlsx", views.billing_report_xlsx, name="billing_xlsx"),
    path("reports/deals/", views.deals_report, name="deals_report"),
    path("reports/deals.xlsx", views.deals_report_xlsx, name="deals_report_xlsx"),
    path("reports/deals/users/", views.deals_users_report, name="deals_users_report"),
    path("reports/deals/users.xlsx", views.deals_users_report_xlsx, name="deals_users_report_xlsx"),
    path("reports/deals/cities/", views.deals_cities_report, name="deals_cities_report"),
    path("reports/deals/cities.xlsx", views.deals_cities_report_xlsx, name="deals_cities_report_xlsx"),
    path("reports/classifieds/", views.classifieds_stats_report, name="classifieds_stats"),
    path("users/", views.users_list, name="users"),
    path("users/<int:user_id>/", views.user_detail, name="user_detail"),
    path("users/<int:user_id>/bookings.xlsx", views.user_bookings_xlsx, name="user_bookings_xlsx"),
    path("users/<int:user_id>/reviews.xlsx", views.user_reviews_xlsx, name="user_reviews_xlsx"),
    path("users.xlsx", views.users_list_xlsx, name="users_xlsx"),
    path("users/<int:user_id>/activate/", views.user_activate, name="user_activate"),
    path("users/<int:user_id>/deactivate/", views.user_deactivate, name="user_deactivate"),
    path("users/<int:user_id>/role/", views.user_set_role, name="user_set_role"),
    path("users/<int:user_id>/sto-moderation/approve/", views.user_sto_approve, name="user_sto_approve"),
    path("users/<int:user_id>/sto-moderation/set/", views.user_sto_set_moderation, name="user_sto_set_moderation"),
    path("bookings/", views.bookings_list, name="bookings"),
    path("bookings/<int:booking_id>/", views.booking_detail, name="booking_detail"),
    path("bookings.xlsx", views.bookings_list_xlsx, name="bookings_xlsx"),
    path("bookings/<int:booking_id>/status/", views.booking_set_status, name="booking_set_status"),
    path("bookings/<int:booking_id>/cancel/", views.booking_emergency_cancel, name="booking_emergency_cancel"),
    path("support/", views.support_list, name="support"),
    path("support/<int:ticket_id>/", views.support_ticket_detail, name="support_ticket_detail"),
    path("support/<int:ticket_id>/reply/", views.support_ticket_reply, name="support_ticket_reply"),
    path("support/<int:ticket_id>/status/", views.support_ticket_set_status, name="support_ticket_set_status"),
    path("reviews/", views.reviews_list, name="reviews"),
    path("reviews/<int:review_id>/", views.review_detail, name="review_detail"),
    path("reviews.xlsx", views.reviews_list_xlsx, name="reviews_xlsx"),
    path("reviews/<int:review_id>/hide/", views.review_hide, name="review_hide"),
    path("reviews/<int:review_id>/publish/", views.review_publish, name="review_publish"),
    path("complaints/<int:complaint_id>/accept/", views.complaint_accept, name="complaint_accept"),
    path("complaints/<int:complaint_id>/reject/", views.complaint_reject, name="complaint_reject"),
    path("stations/", views.stations_list, name="stations"),
    path("stations/<int:station_id>/", views.station_detail, name="station_detail"),
    path("stations/<int:station_id>/activate/", views.station_activate, name="station_activate"),
    path("stations/<int:station_id>/deactivate/", views.station_deactivate, name="station_deactivate"),
    path("stations/<int:station_id>/subscription/", views.station_set_subscription, name="station_set_subscription"),
    path("stations/<int:station_id>/bookings.xlsx", views.station_bookings_xlsx, name="station_bookings_xlsx"),
    path("stations/<int:station_id>/reviews.xlsx", views.station_reviews_xlsx, name="station_reviews_xlsx"),
    path("stations/<int:station_id>/payments.xlsx", views.station_payments_xlsx, name="station_payments_xlsx"),
    path("stations.xlsx", views.stations_list_xlsx, name="stations_xlsx"),
]

