# Generated by Django 5.2.13 on 2026-06-01 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('resolved', 'Закрыто')], db_index=True, default='active', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл')),
            ],
            options={
                'verbose_name': 'Запрос помощи',
                'verbose_name_plural': 'Запросы помощи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='driver_help_status_4e5ea8_idx')],
            },
        ),
    ]
