# Generated by Django 5.2.13 on 2026-04-24 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreview',
            name='photo',
            field=models.TextField(blank=True, help_text='Необязательно, не более одного файла.', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), message='Допустимы только изображения JPG, PNG или WEBP.')], verbose_name='Фото'),
        ),
    ]
