# Generated by Django 5.2.13 on 2026-06-01 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProblemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('car_brand', models.CharField(blank=True, default='', max_length=80, verbose_name='Марка авто')),
                ('city_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('claimed', 'В работе'), ('closed', 'Закрыта')], db_index=True, default='open', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_problem_posts', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_problems_claimed', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Проблема водителя',
                'verbose_name_plural': 'Проблемы водителей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='driver_prob_status_fbf664_idx')],
            },
        ),
    ]
