# Generated by Django 5.2.13 on 2026-04-15 12:51

import apps.chat.models
import apps.chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_5feac5_idx',
            old_name='chat_messa_room_id_8a7f96_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.chat.models.chat_attachment_upload_to, validators=[apps.chat.validators.validate_chat_attachment]),
        ),
    ]
