# Generated by Django 5.2.13 on 2026-04-23 07:49

import apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_stationdirectthread_client_read_up_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64, verbose_name='Тип')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Toast-уведомление',
                'verbose_name_plural': 'Toast-уведомления',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RenameIndex(
            model_name='chatroomlastread',
            new_name='chat_chatro_room_id_2a8922_idx',
            old_name='chat_last_r_room_id_7c6a9b_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroomlastread',
            new_name='chat_chatro_user_id_850466_idx',
            old_name='chat_last_r_user_id_8a5bb2_idx',
        ),
        migrations.RenameIndex(
            model_name='stationdirectmessage',
            new_name='chat_statio_thread__3ebd06_idx',
            old_name='chat_stadirec_thread_2c3d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='stationdirectthread',
            new_name='chat_statio_station_e254bc_idx',
            old_name='chat_stadirec_station_1b6782_idx',
        ),
        migrations.RenameIndex(
            model_name='stationdirectthread',
            new_name='chat_statio_station_be2935_idx',
            old_name='chat_stadirec_station_0a1b2c_idx',
        ),
        migrations.AlterField(
            model_name='chatroomlastread',
            name='last_read_at',
            field=models.DateTimeField(default=apps.chat.models.chat_epoch),
        ),
        migrations.AddField(
            model_name='usertoastevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toast_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='usertoastevent',
            index=models.Index(fields=['user', 'seen_at', '-created_at'], name='chat_userto_user_id_aad62b_idx'),
        ),
    ]
