# Generated by Django 5.2.13 on 2026-04-25 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_usertoastevent_and_more'),
        ('classifieds', '0005_ad_car_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDirectThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_read_up_to', models.DateTimeField(blank=True, null=True, verbose_name='Покупатель просмотрел сообщения до')),
                ('seller_read_up_to', models.DateTimeField(blank=True, null=True, verbose_name='Продавец просмотрел сообщения до')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_threads', to='classifieds.ad', verbose_name='Объявление')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_buyer_threads', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_seller_threads', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Чат по объявлению',
                'verbose_name_plural': 'Чаты по объявлениям',
            },
        ),
        migrations.CreateModel(
            name='AdDirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.addirectthread', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение (чат по объявлению)',
                'verbose_name_plural': 'Сообщения (чаты по объявлениям)',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='addirectthread',
            index=models.Index(fields=['seller', '-last_message_at'], name='chat_addire_seller__e448be_idx'),
        ),
        migrations.AddIndex(
            model_name='addirectthread',
            index=models.Index(fields=['buyer', '-last_message_at'], name='chat_addire_buyer_i_eafbb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='addirectthread',
            constraint=models.UniqueConstraint(fields=('ad', 'buyer'), name='ad_direct_thread_unique'),
        ),
        migrations.AddIndex(
            model_name='addirectmessage',
            index=models.Index(fields=['thread', 'created_at'], name='chat_addire_thread__cfc28f_idx'),
        ),
    ]
